/**
 * Copyright © 2017 Hefei Wo Yi Information Technology Co., Ltd All rights reserved.
 * 
 * @Title Account.java
 * @Package com.woyi.ydzw.account.domain
 * @author ypzhang@woyitech.com
 * @date 2017-05-03 09:29:20
 * @version  V1.0
*/
package com.zcs.account.domain;

import java.util.ArrayList;
import java.util.List;

import javax.validation.constraints.Min;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;


/**
 * 模型管理类
 * @see
 * @author huangchaoyang
 * @date 2017年5月3日 下午
 * @version
 * @desc TODO
 */
public class Account {
	/**
	 * 序列号
	 */
	private static final long serialVersionUID = 5227250296669477739L;
	/**
	 * 科目金额
	 */
	private double count = 0.00;
	/**
	 * 同层科目金额
	 */
	private double countSame = 0.00;
	/**
	 * 子类
	 */
	private List<String> subAccounts;
	/**
	 * 是否有子类
	 */
	private boolean haveSub = true;

	/**
	 * 添加子级科目
	 * @param id
	 */
	public void addSubAccounts(String id) {
		if (subAccounts == null) {
			subAccounts = new ArrayList<>();
		}
		subAccounts.add(id);
	}
	/**
	 * addCountSame
	 * @param c
	 */
	public void addCountSame(double c) {
		countSame += c;
	}
	/**
	 * addCount
	 * @param c
	 */
	public void addCount(double c) {
		count += c;
	}
	/**
	 * getCount
	 * @return the count
	 */
	public double getCount() {
		return count;
	}
	/**
	 * setCount
	 * @param count the count to set
	 */
	public void setCount(double count) {
		this.count = count;
	}

	/**
	 * 新增数据标志性接口
	 * @author Administrator
	 */
	public interface Add {
	}

	/**
	 * 编辑数据标志性接口
	 * @author Administrator
	 */
	public interface Edit {
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * t_account.id
	 * @mbggenerated 2017-05-03 09:29:20
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * t_account.name
	 * @mbggenerated 2017-05-03 09:29:20
	 */
	@NotBlank(groups = { Add.class, Edit.class }, message = "科目名称不能为空")
	@Length(min = 1, max = 50, groups = { Add.class, Edit.class }, message = "科目名称长度在1到50之间")
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * t_account.code
	 * @mbggenerated 2017-05-03 09:29:20
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * t_account.parentid
	 * @mbggenerated 2017-05-03 09:29:20
	 */
	private String parentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * t_account.sort
	 * @mbggenerated 2017-05-03 09:29:20
	 */
	@Min(value=0,groups={Add.class,Edit.class})
	private Integer sort;
	/**
	 * 查询时间
	 */
	private String endtimeStr;
	/**
	 * order
	 */
	private Integer order;
	/**
	 * 上级科目
	 */
	private String parentName;
	/**
	 * 单位ID
	 */
	private String companyId;

	/**
	 * getParentName
	 * @return String
	 */
	public String getParentName() {
		return parentName;
	}
	/**
	 * setName
	 */
	public void setParentName(String parentName) {
		this.parentName = parentName;
	}
	/**
	 * getOrder
	 * @return Integer
	 */
	public Integer getOrder() {
		return order;
	}
	/**
	 * setOrder
	 */
	public void setOrder(Integer order) {
		this.order = order;
	}
	/**
	 * getId
	 * @return String
	 */
	public String getId() {
		return id;
	}
	/**
	 * sets . This method was generated by MyBatis Generator. This method sets the value of the
	 * database column t_account.id
	 * @param id the value for t_account.id
	 * @mbggenerated 2017-05-03 09:29:20
	 */
	public void setId(String id) {
		this.id = id;
	}
	/**
	 * . This method was generated by MyBatis Generator. This method returns the value of the
	 * database column t_account.name
	 * @return the value of t_account.name
	 * @mbggenerated 2017-05-03 09:29:20
	 */
	public String getName() {
		return name;
	}
	/**
	 * sets . This method was generated by MyBatis Generator. This method sets the value of the
	 * database column t_account.name
	 * @param name the value for t_account.name
	 * @mbggenerated 2017-05-03 09:29:20
	 */
	public void setName(String name) {
		this.name = name;
	}
	/**
	 * . This method was generated by MyBatis Generator. This method returns the value of the
	 * database column t_account.code
	 * @return the value of t_account.code
	 * @mbggenerated 2017-05-03 09:29:20
	 */
	public String getCode() {
		return code;
	}
	/**
	 * sets . This method was generated by MyBatis Generator. This method sets the value of the
	 * database column t_account.code
	 * @param code the value for t_account.code
	 * @mbggenerated 2017-05-03 09:29:20
	 */
	public void setCode(String code) {
		this.code = code;
	}
	/**
	 * . This method was generated by MyBatis Generator. This method returns the value of the
	 * database column t_account.parentid
	 * @return the value of t_account.parentid
	 * @mbggenerated 2017-05-03 09:29:20
	 */
	public String getParentid() {
		return parentid;
	}
	/**
	 * sets . This method was generated by MyBatis Generator. This method sets the value of the
	 * database column t_account.parentid
	 * @param parentid the value for t_account.parentid
	 * @mbggenerated 2017-05-03 09:29:20
	 */
	public void setParentid(String parentid) {
		this.parentid = parentid;
	}
	/**
	 * . This method was generated by MyBatis Generator. This method returns the value of the
	 * database column t_account.sort
	 * @return the value of t_account.sort
	 * @mbggenerated 2017-05-03 09:29:20
	 */
	public Integer getSort() {
		return sort;
	}
	/**
	 * sets . This method was generated by MyBatis Generator. This method sets the value of the
	 * database column t_account.sort
	 * @param sort the value for t_account.sort
	 * @mbggenerated 2017-05-03 09:29:20
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}
	/**
	 * 获取单位ID
	 * @return String
	 */
	public String getCompanyId() {
		return companyId;
	}
	/**
	 * 设置单位ID
	 * @param companyId
	 */
	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}
	/**
	 * getEndtimeStr
	 * @return the endtimeStr
	 */
	public String getEndtimeStr() {
		return endtimeStr;
	}
	/**
	 * getSubAccounts
	 * @return the subAccounts
	 */
	public List<String> getSubAccounts() {
		return subAccounts;
	}
	/**
	 * setSubAccounts
	 * @param subAccounts the subAccounts to set
	 */
	public void setSubAccounts(List<String> subAccounts) {
		this.subAccounts = subAccounts;
	}
	/**
	 * isHaveSub
	 * @return the haveSub
	 */
	public boolean isHaveSub() {
		return haveSub;
	}
	/**
	 * setHaveSub
	 * @param haveSub the haveSub to set
	 */
	public void setHaveSub(boolean haveSub) {
		this.haveSub = haveSub;
	}
	/**
	 * setEndtimeStr
	 * @param endtimeStr the endtimeStr to set
	 */
	public void setEndtimeStr(String endtimeStr) {
		this.endtimeStr = endtimeStr;
	}
	/**
	 * getCountSame
	 * @return the countSame
	 */
	public double getCountSame() {
		return countSame;
	}
	/**
	 * setCountSame
	 * @param countSame the countSame to set
	 */
	public void setCountSame(double countSame) {
		this.countSame = countSame;
	}
}
