/**
 * Copyright © 2017 Hefei Wo Yi Information Technology Co., Ltd All rights reserved.
 * 
 * @Title AccountMapper.java
 * @Package com.woyi.ydzw.account.dao
 * @author Administrator
 * @date 2017-05-03 09:29:20
 * @version  V1.0
*/
package com.zcs.demo.account.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.github.pagehelper.Page;
import com.zcs.account.domain.Account;
import com.zcs.MybatisMapper;

/**
 * 报销科目
 * @author wchao
 *
 */
public interface AccountMapper extends MybatisMapper<Account> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     * @param id   java.lang.String
     * @return int
     *
     * @mbggenerated 2017-05-03 09:29:20
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     * @param record   com.woyi.ydzw.account.domain.Account
     * @return int
     *
     * @mbggenerated 2017-05-03 09:29:20
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     * @param id   java.lang.String
     * @return com.woyi.ydzw.account.domain.Account
     *
     * @mbggenerated 2017-05-03 09:29:20
     */
    Account selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     * @param record   com.woyi.ydzw.account.domain.Account
     * @return int
     *
     * @mbggenerated 2017-05-03 09:29:20
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     * @param record   com.woyi.ydzw.account.domain.Account
     * @return int
     *
     * @mbggenerated 2017-05-03 09:29:20
     */
    int updateByPrimaryKey(Account record);

    /**
     * 查询所有报销科目
     * @return List
     */
	List<Account> getAllAcounts(@Param("companyId")String companyId);
	/** 
	 * 根据id删除信息
	 * @Title deleteAccountById 
	 * @author huangchaoyang
	 * @param id
	 * @return int
	 */
	int deleteAccountByIds(@Param("ids")String[] ids);
	
	/**
	 * 根据parentid查询报销科目
	 * @return list
	 * @throws Exception
	 */
	List<Account> selectByParentId(@Param("account")  Account account);
	/**
	 * 根据parentid查询所有报销子科目
	 * @return list
	 * @throws Exception
	 */
	List<Account> selectChildsByParentId(@Param("account")  Account account);

	/**
	 * 根据name查询报销科目
	 * @return List<Account>
	 * @throws Exception
	 */
	List<Account> selectByName(@Param("account") Account account);
	
}